package: feeds
version: '4.0.0-dev'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/feeds

page:
    title: 'translate:feeds'
    perm: feeds[]
    pjax: true
    icon: rex-icon fa-rss
    subpages:
        streams:
            title: 'translate:streams'
        items:
            title: 'translate:items'
        help:
            title: 'translate:help'
            perm: admin[]
            pjax: false
            subPath: README.md
            itemclass: pull-right

requires:
    redaxo: '^5.14'
    php:
        version: '>=8.1'

conflicts:
    packages:
        yfeed: '<=1.3.0'
        feeds: '<4.0.0-dev'
