package: yfeed
version: '1.0.0'
author: Gregor Harlan, Thomas Blum
supportpage: www.redaxo.org/de/forum/

page:
    title: 'translate:yfeed'
    perm: yfeed[]
    pjax: false
    icon: rex-icon fa-rss
    subpages:
        streams:
            title: 'translate:streams'
        responses:
            title: 'translate:response'
        settings:
            title: 'translate:settings'
            subpages:
                twitter:
                    title: 'translate:twitter'
                facebook:
                    title: 'translate:facebook'
